pipeline {
    agent any
    stages {
        stage('Test') {
            steps {
                sh "echo secceful"
            }
        }
        stege('Build static and back') {
            steps {
                dir('skin-guard/pipeline/Docker/front_back')
                    sh "docker compose up ."
            }
        }
        


    }

}
