
pipeline {
  agent any
  options {
  buildDiscarder logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '5')
  }
  stages {
    stage('clean') {
      steps {
        sh 'echo y | docker system prune --all'
        sh 'rm /opt/data/*'
      }
    }
    stage('Build Frontend') {
      steps{
        dir ('client/') {
          sh 'docker build -t front . '
        }
      }
    }
    stage('Build Backend') {
      steps{
        dir ('server/') {
          sh 'docker build -t back .'  
        }
      }
    }
    stage('Deploy to stage') {
      steps {
        dir ('docker/') {
          sh 'docker compose up -d'
        }
      }
    }  
  }
}

